import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from sklearn.preprocessing import MinMaxScaler

print("Starting Layer 2: Unsupervised ANN (Autoencoder)...")

# 1. Load the data generated by Layer 1
filename = "layer1_EPHE_data.csv"
try:
    data = pd.read_csv(filename)
    print(f"Successfully loaded {len(data)} rows of data.")
except FileNotFoundError:
    print(f"Error: Could not find {filename}. Did you run layer1_data.py?")
    exit()

# 2. Prepare the data
# Neural Networks only like numbers, so we select only the numeric trading columns.
# We ignore the 'Date' column for the math part, but we will keep it for the final report.
features = ['Open', 'High', 'Low', 'Close', 'Volume']
market_data = data[features].copy()

# 3. Scale the data (Crucial for Neural Networks)
# Stocks might trade at $25, but volume is 300,000. Big numbers overpower small numbers.
# MinMaxScaler squishes all numbers to be between 0 and 1 so the network treats them equally.
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(market_data)

# 4. Build the Autoencoder Architecture
# This is a 4-layer Unsupervised Artificial Neural Network
input_dim = len(features) # We have 5 features

# The Input Layer
input_layer = Input(shape=(input_dim,))

# The Encoder Layer (Compresses the 5 features down to 3)
encoded = Dense(3, activation='relu')(input_layer)

# The Bottleneck (Compresses it further down to 2 core concepts)
bottleneck = Dense(2, activation='relu')(encoded)

# The Decoder Layer (Tries to rebuild the 3 features)
decoded = Dense(3, activation='relu')(bottleneck)

# The Output Layer (Reconstructs the original 5 features)
output_layer = Dense(input_dim, activation='linear')(decoded)

# Combine layers into the final model
autoencoder = Model(inputs=input_layer, outputs=output_layer)
autoencoder.compile(optimizer='adam', loss='mse') # 'mse' means Mean Squared Error

# 5. Train the Model (Unsupervised)
# Notice how 'x' and 'y' are BOTH scaled_data. 
# It is unsupervised because we don't give it answers; we ask it to recreate its own input!
print("\nTraining the Autoencoder... (This might take a few seconds)")
autoencoder.fit(scaled_data, scaled_data, epochs=50, batch_size=8, shuffle=True, verbose=0)
print("Training complete!")

# 6. Detect Anomalies
# We ask the trained model to reconstruct all 125 days.
reconstructions = autoencoder.predict(scaled_data)

# We calculate the "Mistake Score" (Mean Squared Error) for each day
# If the mistake is small, the day was normal. If the mistake is huge, it's an anomaly!
mse = np.mean(np.power(scaled_data - reconstructions, 2), axis=1)

# Let's say any day in the top 5% of mistakes is an "Anomaly"
threshold = np.percentile(mse, 95)

# Add our findings back to the original data
data['Anomaly_Score'] = mse
data['Is_Anomaly'] = data['Anomaly_Score'] > threshold

# 7. Show the results!
anomalies = data[data['Is_Anomaly'] == True]

print(f"\nFound {len(anomalies)} anomalous days in the dataset!")
print("Here are the dates where the market behaved weirdly:")
print(anomalies[['Date', 'Close', 'Volume', 'Anomaly_Score']])

# 8. Save the results for Layer 3 (The LLM Layer)
output_filename = "layer2_anomalies.csv"
data.to_csv(output_filename, index=False)
print(f"\nAll data (with anomaly flags) saved to {output_filename}")