/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns the status of the API and model loading.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Returns the current API version.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forecast
         * @description Accepts historical price data and returns quantile predictions.
         */
        post: operations["forecast_api_v1_forecast__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trading/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Trade Endpoint
         * @description Triggers the hybrid decision engine to evaluate a trade for a given ticker.
         *     This runs both the AI signal generation and Rule-Based safety gates.
         */
        post: operations["evaluate_trade_endpoint_api_v1_trading_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trading/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Override Endpoint
         * @description Allows authorized manual override of trades. Still logs the reasoning for auditability.
         */
        post: operations["manual_override_endpoint_api_v1_trading_override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIRecommendation */
        AIRecommendation: {
            action: components["schemas"]["TradeAction"];
            /** Confidence Score */
            confidence_score: number;
            /** Reasoning */
            reasoning: string;
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            /** User Id */
            user_id: string;
            /** Ticker */
            ticker: string;
            /**
             * Lookback Days
             * @default 30
             */
            lookback_days: number;
        };
        /** ForecastRequest */
        ForecastRequest: {
            /**
             * History
             * @description Historical price data points (minimum 10 recommended).
             * @example [
             *       10.5,
             *       11.2,
             *       10.8,
             *       12.1,
             *       11.5,
             *       12,
             *       11.8,
             *       12.5,
             *       13,
             *       12.8
             *     ]
             */
            history: number[];
            /**
             * Prediction Length
             * @description Number of future steps to forecast.
             * @default 24
             * @example 24
             */
            prediction_length: number;
            /**
             * Quantiles
             * @description Quantile levels for probabilistic forecasting.
             * @default [
             *       0.1,
             *       0.5,
             *       0.9
             *     ]
             * @example [
             *       0.1,
             *       0.5,
             *       0.9
             *     ]
             */
            quantiles: number[];
        };
        /** ForecastResponse */
        ForecastResponse: {
            /**
             * Forecasts
             * @description Dictionary mapping quantiles to predicted value lists.
             * @example {
             *       "q_0.1": [
             *         12.5,
             *         12.4
             *       ],
             *       "q_0.5": [
             *         13.1,
             *         13.2
             *       ],
             *       "q_0.9": [
             *         13.8,
             *         14.1
             *       ]
             *     }
             */
            forecasts: {
                [key: string]: number[];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OverrideRequest */
        OverrideRequest: {
            /** User Id */
            user_id: string;
            /** Ticker */
            ticker: string;
            action: components["schemas"]["TradeAction"];
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
        };
        /**
         * TradeAction
         * @enum {string}
         */
        TradeAction: "BUY" | "SELL" | "HOLD";
        /** TradeDecision */
        TradeDecision: {
            /** Ticker */
            ticker: string;
            action: components["schemas"]["TradeAction"];
            /**
             * Quantity
             * @default 0
             */
            quantity: number;
            /** Target Price */
            target_price?: number | null;
            /** Is Approved */
            is_approved: boolean;
            ai_signal: components["schemas"]["AIRecommendation"];
            /** Rule Gate Reasoning */
            rule_gate_reasoning: string;
            /** Portfolio Impact */
            portfolio_impact?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    forecast_api_v1_forecast__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_trade_endpoint_api_v1_trading_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_override_endpoint_api_v1_trading_override_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
